public class NPAAInputWrapper {


    @AuraEnabled
    public string Name;

    @AuraEnabled
    public string existingAccountId;

    @AuraEnabled
    public String selectedOrgType;

    @AuraEnabled
    public String selectedBusinessType;

    @AuraEnabled
    public String selectedOrgSubType;

    @AuraEnabled
    public String selectedAccountType;

    @AuraEnabled
    public String selectedAccessType;

    @AuraEnabled
    public String selectedProductItem;

    @AuraEnabled
    public String selectedCampaign;

    @AuraEnabled
    public String selectedHowHear;

    @AuraEnabled
    public String selectedOrgName;
        
}